name: "opensyd_providers"
author: Sergio Lisan <sels@venosyd.com>
publish_to: "none"

version: 3.0.1+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  archive:
  opensyd_dart:
    git: https://github.com/venosyd/opensyd_dart
